# -*- coding: utf-8 -*-
"""TA_Lab_04_group_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxY_vqbiG88qfPgSHsC1rhzzSZ_Slhaw

Q1. Ask the user to enter a string, then print that string 100 times, separated by a space. For example, if the user enters hi, the output should be: hi hi hi hi hi hi hi ... (a total of 100 times)
"""

user_input = input("Enter a string: ")
result = (user_input + " ") * 100
print(result.strip())

"""Q2. Write a program to test whether a string is a palindrome, which means the reversed string is the same as the original one. Example: rester"""

palindrome_input = input('input string: ')

if palindrome_input == palindrome_input[::-1]:
    print("This string is a palindrome")
else:
    print("This string is not a palindrome")

"""Q3.Given the sorted sequence [1,12,14,21,23,36,43,48,56,78,89,102,126,147,168,171,199,222,256,348], find the median (use len to calculate, do not directly substitute the number)."""

data = [1, 12, 14, 21, 23, 36, 43, 48, 56, 78, 89, 102, 126, 147, 168, 171, 199, 222, 256, 348]

n = len(data)
if n % 2 == 1:

    median = data[n // 2]
else:
    middle1 = data[n // 2 - 1]
    middle2 = data[n // 2]
    median = (middle1 + middle2) /2

print(f"The length of the list is: {n}")
print(f"The median is: {median}")